[project]
name = "ml-chord-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.3.0",
    "pytorch-lightning>=2.5.5",
    "tensorboard>=2.20.0",
    "torch>=2.9.0",
]
